DOC_CATEGORIES = {
    "1. Intelligence & Prompting": {
        "1.1 Instruction Styles": (
            "Large Language Models fundamentally differ in how they interpret system prompts based on their underlying architecture.\n\n"
            "**Traditional Models (e.g., Gemini 2.0 Flash, GPT-3.5, Claude Haiku 3):**\n"
            "These models act as highly probable next-token predictors. To keep them on track, they require intricate **AI Instructions**—such as explicit formatting rules, strict negative constraints, and forced 'think step-by-step' (Chain of Thought) commands.\n\n"
            "**Reasoning Models (e.g., Gemini 3 Flash, GPT 5.4 Mini, DeepSeek V3.2):**\n"
            "These models possess a built-in, native deliberation phase where they generate an internal Chain of Thought before outputting text. Research indicates that overloading these models with micromanaged formatting, manual step-by-step instructions, or extensive few-shot examples actually disrupts their performance and can cause intent drift. For reasoning models, the best practice is to *'suggest the destination, but don't force the journey'*. Keep your AI Instructions (found under `/profile manage` -> **Edit Instructions**) clear, direct, and minimal to allow their native cognitive processes to flourish."
        ),
        "1.2 Enhancing Intelligence": (
            "You can push your profile's cognitive capabilities to their limits using the `/profile manage` dashboard.\n\n"
            "• **Model Upgrades:** Selecting a frontier reasoning model (e.g., `gemini-3.1-pro` or OpenRouter equivalents like `claude-sonnet-4.6`) via the **Set Models** menu dramatically increases logical comprehension for complex roleplay scenarios.\n"
            "• **Web Grounding:** Enabling **Grounding** gives the AI access to real-time Google Searches. Instead of relying solely on static training weights, it can dynamically pull factual data to anchor its responses to the real world. Switching this to **RAG** mode ensures it works seamlessly across all expanded custom OpenRouter models.\n"
            "• **Context Expansion:** Increasing the **STM Length** or expanding **LTM Context Size** provides the bot with a richer historical tapestry to draw from, making conversations feel significantly more cohesive and grounded."
        ),
        "1.3 Reducing Latency": (
            "High intelligence and vast context windows often come at the cost of generation speed. If your profile feels sluggish, you can optimize its response time through the dashboard:\n\n"
            "• **Lower Thinking Effort:** For reasoning models, reducing the **Thinking Level** (e.g., from High to Minimal) or capping the **Reasoning Token Budget** forces the model to conclude its internal deliberation much faster.\n"
            "• **Disable the Critic:** The Anti-Repetition Critic runs a secondary AI evaluation to detect linguistic loops before sending a message. Disabling it cuts the required API calls in half.\n"
            "• **Disable External Tools:** Turning off **Grounding** and **URL Fetching** bypasses the heavy overhead of web scraping and search indexing.\n"
            "• **Model Downgrade:** Switching your primary model to a lightning-fast variant like `gemini-2.5-flash-lite` will yield near-instantaneous replies at the cost of some logical reasoning depth."
        )
    },
    "2. Generation Parameters": {
        "2.1 Core Sampling (Temp, Top K, Top P)": (
            "These fundamental parameters, adjustable via **Set Generation Parameters & STM**, control the model's creativity:\n\n"
            "• **Temperature (0.0 - 2.0):** Controls overall randomness. A low value (e.g., 0.3) produces highly analytical and predictable text. A high value (e.g., 1.5) encourages chaotic, wildly creative responses.\n"
            "• **Top K:** Hard-limits the AI's vocabulary to the *K* most likely next words. A Top K of 40 means the model only ever considers the top 40 options, cutting off the 'tail' of complete gibberish.\n"
            "• **Top P (Nucleus Sampling):** Dynamically shrinks or expands the vocabulary pool by adding top words until their combined probability reaches *P* (e.g., 0.90). It forces the AI to play it safe when unsure, but allows diverse choices when confident."
        ),
        "2.2 Advanced Sampling (Min P, Top A)": (
            "Available for OpenRouter models via **Set Advanced Parameters**, these offer superior dynamic filtering:\n\n"
            "• **Min P (0.0 - 1.0):** An adaptive threshold that scales relative to the most likely token's confidence. If the top token has a 50% probability and Min P is 0.1, any token below 5% (1/10th of 50%) is ignored. It perfectly balances coherence and diversity, often outperforming Top P at higher temperatures.\n"
            "• **Top A (0.0 - 1.0):** Truncates the selection pool based on the *square* of the highest token's probability. It aggressively prunes bad options when the model is highly confident, making it an excellent tool for maintaining quality during creative writing without sacrificing structure."
        ),
        "2.3 Repetition Penalties": (
            "Also located in **Set Advanced Parameters**, these settings punish the AI for sounding like a broken record:\n\n"
            "• **Frequency Penalty (-2.0 - 2.0):** Reduces the probability of words based on how *often* they have already been used in the generated text. This strongly encourages the bot to utilize a more diverse vocabulary.\n"
            "• **Presence Penalty (-2.0 - 2.0):** Applies a flat, one-time penalty to any word that has appeared at least once. This pushes the model to pivot to entirely new topics or concepts rather than lingering on the same subject.\n"
            "• **Repetition Penalty:** A direct, multiplicative penalty applied to recently generated tokens to forcefully break the AI out of infinite stuttering loops."
        )
    },
    "3. XML & Coherence Metadata": {
        "3.1 The XML Partitioning Protocol": (
            "To maintain strict boundaries between the user's conversation and the system's background processes, MimicAI wraps supplementary data in XML tags. Large Language Models possess a high mechanical affinity for XML, allowing them to instantly differentiate between 'what the user said' and 'what the system is instructing it to know'.\n\n"
            "**Common Tags:**\n"
            "• `<archive_context>`: Recalled Long-Term Memories.\n"
            "• `<external_context>`: Real-time Google Search summaries (Grounding).\n"
            "• `<document_context>`: Text scraped from URLs provided in the chat.\n"
            "• `<time_context>`: The profile's current localised time and date.\n"
            "• `<whisper_context>` / `<private_response>`: Ephemeral, hidden messages sent between users and profiles.\n"
            "• `<internal_note>`: Systemic prompts used to initiate or guide the generation loop without appearing in the public chat."
        ),
        "3.2 Chronological & Identity Headers": (
            "To ensure coherent multi-participant tracking, the system forcibly injects a strict header before every single message in the session.\n\n"
            "**Format:** `Name [ID: XXXXXXXXXXXXXXXX] [Day, DD Mon YYYY, HH:MM AM/PM TZ]:`\n\n"
            "• **Identity Verification:** The 16-character PID (Profile ID) ensures the AI never confuses two characters with the same name.\n"
            "• **Temporal Awareness:** Embedding the exact timestamp of every message gives the AI perfect chronological awareness. It inherently understands if an hour, a day, or a week has passed between messages without needing explicit reminders, maintaining seamless roleplay continuity."
        ),
        "3.3 Hidden Generation Metadata": (
            "If 'Generation Metadata' is enabled via `/profile manage`, the system appends a hidden line to the end of the AI's response in the internal history buffer (e.g., `(Thought Initiated: 02:30 PM | Duration: 4.25s)`).\n\n"
            "While this is optionally visible in the Discord chat as subtext, its primary purpose is systemic. By feeding the generation duration and precise initiation time back into the model's context window, the AI gains an intrinsic understanding of its own operational latency and network delays, further grounding it in the reality of the live session."
        )
    }
}

HELP_CATEGORIES = {
    "1. Introduction & Auth": {
        "Authentication Requirements": "This system requires API authentication to function. All generation tasks are passed to external inference endpoints.\n\n**Primary Authentication (Google Gemini):**\n1. Acquire a standard API key via Google AI Studio.\n2. Execute the `/settings` command via Direct Message to access the configuration panel.\n\n**Secondary Authentication (OpenRouter):**\n1. Acquire an API key via OpenRouter to utilise alternative models (e.g., Anthropic, Meta).\n\n**Key Pool Mechanism:**\nAdministrators may set a 'Primary Key' for server-wide execution. Users may also contribute personal keys to the 'Pool'. The system will cycle through valid keys in the pool if the Primary Key is exhausted.",
        "System Architecture Overview": "MimicAI operates as a multimodal orchestration layer. It manages character state, session history, and external API requests.\n\nThe system is built upon a 'Profile' architecture. A Profile acts as a container for system instructions, inference parameters, and persistent memory. These profiles are executed within 'Sessions'—isolated conversational contexts tied to specific channels or direct messages.\n\nUse the dropdown menus below to navigate the technical documentation.",
        "Profile Classes": "The system distinguishes between two classes of Profiles:\n\n**Personal Profiles:**\nThese are primary entities owned and maintained by the user. The owner possesses full read/write privileges over generation parameters, memory vectors, and systemic instructions.\n\n**Borrowed Profiles:**\nThese are read-only symbolic links to another user's Personal Profile, acquired via the Public Library or direct share code. Local configuration (such as temporal awareness and formatting) may be overridden, but core identity variables remain synchronised with the origin.",
        "Persona Definition": "The core identity of a Profile is constructed using modular text fields that are compiled into XML-tagged system instructions during inference.\n\nThe Persona module comprises:\n- **Backstory:** Historical and contextual data.\n- **Personality Traits:** Core psychological characteristics.\n- **Likes/Dislikes:** Positive and negative biases.\n- **Appearance:** Physical description (utilised heavily by the Visual Generation module for self-portraits).",
        "AI Instruction Protocol": "AI Instructions dictate operational behaviour and formatting constraints. These bypass the Persona module and instruct the underlying model on strict structural adherence.\n\nThe interface provides four distinct data blocks to prevent context truncation. It is recommended to utilise standard declarative constraints (e.g., 'Do not output markdown', 'Keep responses under two sentences'). These instructions take priority over persona biases during generation.",
        "Redundancy (Model Fallback)": "The system features a fault-tolerant generation loop. If the primary inference request fails due to rate limits, server timeouts, or strict safety blocks, the system automatically redirects the payload to the defined Fallback Model.\n\nIt is highly recommended to designate an efficient, low-cost model (e.g., `gemini-flash-lite-latest`) as the fallback to maintain uptime during primary endpoint degradation."
    },
    "2. Generation & Modifiers": {
        "Generation Parameters": "Users may manipulate the statistical variance of the output via standard sampling parameters:\n\n- **Temperature:** Controls the randomness of token selection. Lower values yield deterministic outputs; higher values yield diverse outputs.\n- **Top P (Nucleus Sampling):** The model considers only the tokens comprising the top probability mass. Set to 1.0 to disable.\n- **Top K:** Limits the token selection pool to the K most probable tokens.\n- **STM Length:** Short-Term Memory. Defines how many previous conversational turns are appended to the context window.",
        "Advanced Heuristics (OpenRouter)": "For endpoints supporting OpenRouter specifications, additional penalisation parameters are available:\n\n- **Frequency Penalty (-2.0 to 2.0):** Applies an additive penalty to tokens based on their existing frequency in the text, reducing verbatim repetition.\n- **Presence Penalty (-2.0 to 2.0):** Applies an absolute penalty if a token exists at all, encouraging topic divergence.\n- **Repetition Penalty:** Multiplicative penalty against recently generated tokens.\n- **Min P / Top A:** Advanced thresholding metrics to dynamically cull low-probability tokens.",
        "Reasoning Configuration": "Specific models (e.g., Gemini 2.0 Flash Thinking, Gemini 3.0) support overt reasoning phases prior to text generation.\n\n- **Thinking Level:** Determines the computational effort allocated to reasoning (None, Minimal, Low, Medium, High, XHigh).\n- **Token Budget:** For models that accept explicit limits (e.g., Gemini 2.5), dictates the exact token cap allocated to internal thought.\n- **Summary Visibility:** Toggles whether the raw reasoning tokens are exported and delivered as an attachment alongside the response.",
        "Output Modification: Anti-Repetition Critic": "The Critic module acts as an automated linguistic quality assurance layer.\n\nWhen enabled, the system reviews the last three model outputs prior to execution. If structural repetition is detected (e.g., reusing identical opening phrases or structural loops common in auto-regressive models), it formulates a negative constraint. This constraint is injected into the prompt, explicitly banning the repetitive pattern for the impending turn.",
        "Output Modification: Typing Simulation": "Realistic Typing simulates human interface delays.\n\nThe output string is parsed via regex to identify sentence boundaries (accounting for standard abbreviations). The execution loop calculates a reading/typing delay based on character volume. Sentences are sequentially transmitted to the Discord Webhook API, creating a fragmented, continuous stream of text rather than a single monolithic block.",
        "Temporal Awareness Integration": "If Time Tracking is enabled, the execution loop parses the profile's designated IANA Timezone (e.g., `Europe/London`).\n\nA UTC datetime object is shifted to the local equivalent and formatted into a human-readable string. This data is injected as `<time_context>` into the system prompt, ensuring the model maintains continuity regarding the time of day, day of the week, and date."
    },
    "3. Multimodal & Web": {
        "Web Grounding": "Grounding enables real-time information retrieval via Google Search.\n\n**Modes:**\n- **Native:** Uses Google's internal search tool. Highly accurate and provides inline citations, but **ONLY works with official Google Gemini models** (not OpenRouter or custom models).\n- **RAG (Recommended):** Uses a background agent to search and summarize data before feeding it to your profile. This mode is **model-agnostic**, meaning it works with *any* custom or OpenRouter model.\n\nIt is highly recommended to use **RAG mode** to ensure compatibility across all expanded custom models.",
        "URL Context": "If URL Context Fetching is enabled, the system can extract and read content from links provided in chat.\n\n**Modes:**\n- **Native:** Uses Google's backend to securely fetch up to 34MB of data (including PDFs). However, this **ONLY works with official Google Gemini models**.\n- **RAG (Recommended):** Uses a custom headless scraper to extract HTML/Text. This mode is **model-agnostic** and works with *any* custom or OpenRouter model.\n\nIt is highly recommended to use **RAG mode** for maximum compatibility.",
        "Visual Generation & Processing": "Profiles may generate `.png` visuals using the `!image` or `!imagine` prefix.\n\nThis requires a paid-tier Google API key routing to the `gemini-2.5-flash-image` endpoint. The generation prompt automatically appends the profile's `Appearance` data if second-person pronouns are detected. Once the image is generated, it is fed back into the text model to produce an in-character comment attached to the resulting file.\n\nTo execute style transfers or iterative edits, reply to an existing image with the `!image` command.",
        "Text-To-Speech (Director's Desk)": "The Director's Desk provides semantic priming for the Text-to-Speech (TTS) module.\n\nInstead of raw audio manipulation, the TTS engine is a generative model capable of inferring tone from contextual metadata. Users may define:\n- **Archetype:** E.g., 'A grizzled detective.'\n- **Accent:** E.g., 'Standard British.'\n- **Dynamics:** E.g., 'Speaking in a whisper in a cavern.'\n- **Pacing & Style:** E.g., 'Rapid delivery with a subtle smile.'",
        "Text-To-Speech (Hardware Settings)": "Beyond semantic instruction, explicit TTS hardware configurations include:\n\n- **Voice Name:** The designated prebuilt voice identity (e.g., 'Aoede', 'Kore', 'Charon').\n- **Speech Model:** The backend endpoint (defaults to `gemini-2.5-flash-preview-tts`).\n- **Temperature:** Dictates the expressive variance in the audio generation. Values outside standard 1.0 may result in erratic audio artefacts.",
        "Multimodal Audio Output": "Audio delivery modes modify how the bot processes standard text generation:\n\n- **Text-Only:** Default behaviour.\n- **Audio + Text:** Delivers the primary text payload alongside a synthesised `.wav` attachment.\n- **Audio-Only:** Suppresses the text output, delivering solely the audio file.\n- **Multi-Audio:** In multi-profile sessions, delays audio transmission until the conclusion of the round, stitching all segments into a continuous master file."
    },
    "4. Memory Systems": {
        "Short-Term Memory (STM)": "The STM acts as the immediate conversational buffer. The system maintains a synchronised cache (`unified_log`) representing the chronological sequence of recent interactions.\n\nThis data is hydrated into specific `ChatSession` arrays prior to inference. The depth of this buffer is determined by the profile's STM Length parameter. Exceeding context limits may degrade the model's adherence to systemic instructions. The `/refresh` command flushes this buffer for the current channel.",
        "Long-Term Memory (LTM) Architecture": "The LTM subsystem provides persistent data retention via an automated summarisation pipeline.\n\n**Auto-Creation Pipeline:**\nWhen a user communicates with a profile, an internal counter tracks the exchange volume. Once the `Creation Interval` threshold is met, the system extracts the last `Summarization Context` turns and submits them to an auxiliary model (`gemini-flash-lite`). The model condenses the excerpt into a strict, third-person factual summary.",
        "LTM Retrieval Logistics": "Memories are encoded using Matryoshka Representation Learning (256-dimensional embeddings) and stored locally.\n\nDuring active chat, the user's prompt is embedded and cross-referenced against the profile's memory vault via cosine similarity. If the metric exceeds the profile's `Relevance Threshold`, the top results are injected into the system prompt as `<archive_context>`.\n\n**LTM Scopes:**\n- User: Recalled exclusively for the original author.\n- Server: Recalled for any user within the originating guild.\n- Global: Recalled universally.",
        "Contextual Training Examples": "Training Examples are explicit, user-defined input/output pairs that dictate specific stylistic behaviour.\n\nLike LTMs, they are embedded and retrieved via vector search. Upon matching the `Relevance Threshold`, the pairs are injected into the system instructions. This ensures the model dynamically alters its vernacular, sentence structure, and formatting based on semantic similarities to the user's current prompt. Manage these via `/profile data manage`."
    },
    "5. Session & Freewill": {
        "Standard Session Management": "All conversational interactions occur within Sessions.\n\n**Regular Mode (`/session config`):**\nInitiates a manual session requiring an administrator to define the participating profiles. The operational mode determines execution flow:\n- Sequential: Participants execute in the exact order established during configuration.\n- Random: Execution order is shuffled per round.\n\nStandard `/session swap` operations allow dynamic manipulation of the active cast during runtime.",
        "Session Management: Response Modes": "Profiles may be configured to format their network payload differently depending on use-case requirements:\n\n- **Regular:** Standard webhook message execution.\n- **Mention:** Prepends the user's Discord ID to the message payload.\n- **Reply:** Triggers the Discord API message reference parameter to visually connect the response to the user's prompt.\n- **Mention + Reply:** A hybrid execution of both methodologies.",
        "Session Control via Reactions": "Users may dynamically influence session state and execution flow by applying specific emoji reactions to messages.\n\n- **Regenerate (🔁):** Regenerates a profile's message using the same context that lead to that response.\n- **Next Speaker (⏯️):** Triggers the next profile participant to respond.\n- **Continue Round (🍿):** Triggers a new round for all profile participants to respond.\n- **Mute Turn (🔇):** Hides the targeted message from the session's transcript. The message remains in the channel but becomes invisible to the profiles when they respond.\n- **Skip Participant (❌):** Suspends a specific profile from responding in the session.",
        "Automated Event Scheduling (Freewill)": "The Freewill system enables autonomous bot execution without direct user invocation.\n\nAdministrators classify channels as either 'Living' (fully autonomous) or 'Lurking' (reactive only). Active users must opt their profiles into the system via the configuration dashboard. The system evaluates participation based on the defined 'Personality' percentages (Introverted, Regular, Outgoing), which determine the probability of intervention.",
        "Freewill Mode: Proactive Generation": "In 'Living' channels, an asynchronous loop executes at one-minute intervals.\n\nIf the channel's `Event Cooldown` timer has expired, the system calculates a probability check based on the `Event Chance`. Upon success, it gathers an ad-hoc cast of opted-in profiles and forces a 'Director's Prompt' (e.g., 'You see X walk into the room. React.'). The profiles converse autonomously until the defined proactive round counter depletes.",
        "Freewill Mode: Reactive Triggers": "In both 'Living' and 'Lurking' channels, the system evaluates all standard user messages against the active profiles.\n\nIf a user's text string contains an exact match to a profile's defined 'Wakeword', the profile immediately bypasses standard turn logic to interject. In the absence of wakewords, a probabilistic roll is made against the profile's personality metric to determine random interjection."
    },
    "6. Advanced Architecture": {
        "Inter-Process Communication (Child Bots)": "Child Bots are discrete Discord Application binaries orchestrated by the primary instance (Hivemind).\n\nThe system establishes a WebSocket Inter-Process Communication (IPC) layer on `ws://127.0.0.1:8765`. A background subprocess handles the asynchronous execution of `discord.py` clients. These child instances possess no internal logic; they blindly execute payloads formatted and routed by the primary engine. This allows profiles to exist as independent server members with dedicated online presence.",
        "Child Bot Registration & Sync": "To instantiate a Child Bot:\n1. Register a new Application within the Discord Developer Portal.\n2. Extract the bot token and submit it via `/settings`.\n3. The primary instance encrypts the token, establishes the IPC socket, and dispatches an initialization command.\n\nThe parent instance automatically synchronises the profile's display name and avatar URL to the child application via API calls upon creation or modification.",
        "Public Distribution Index (Hub)": "The Hub (`/profile hub`) operates as a global metadata index for Profile distribution.\n\nPremium users may publish profiles to the index. Upon request, the system executes an automated moderation check using `gemini-flash-lite` to evaluate the profile name, display name, and avatar for graphic or explicit violations. Upon clearance, the profile is appended to the `index.json` structure, allowing global read access for borrowing operations.",
        "Private Distribution (Share Codes)": "For targeted distribution, users may generate temporary cryptographic Share Codes via the Hub interface.\n\nThese codes encode the original owner's ID and the profile string. The generated hex key is retained in a volatile dictionary with a 300-second (5 minute) Time-To-Live (TTL). When a recipient redeems the code, the system validates the TTL, reads the encoded source, and duplicates a symbolic link to their local directory.",
        "Data Import and Export Validation": "Profiles and associated persistent memory (LTM/Training) may be exported to standard `.mimic` JSON files.\n\nThe export function decrypts local storage and packages the dictionaries into plaintext formatting. During import, the system validates the JSON schema, handles namespace collisions via UUID appending, re-encrypts the text blobs, and shunts the data to the appropriate `user_data` and `storage` shards.",
        "System Content Moderation Framework": "The system strictly adheres to external provider usage guidelines regarding illicit content.\n\nUsers may classify profiles under specific safety tiers (Low, Medium, High). The 'Unrestricted 18+' tier disables standard filters; however, execution of these profiles is mathematically restricted by the core engine to channels designated as NSFW via Discord API flags. Attempts to execute unrestricted profiles in standard channels will abort with a silent failure or system error log.",
        "Contextual Metadata & Token Overhead": "To maintain coherent multi-participant communication, the system forcefully injects hardcoded metadata into the prompt payload.\n\nEvery user and profile response within the history buffer is strictly prefixed with a designated `[Name] [Timestamp]:` string. While this incurs a nominal token overhead per conversational turn, it establishes a foundational chronological and spatial awareness for the model. This guarantees the AI can differentiate between multiple actors and comprehend the passage of time without confusing internal dialogue with external user prompts.",
        "Extensible Markup Language (XML) Standards": "The orchestration layer heavily utilises XML formatting (e.g., `<document_context>`, `<archive_context>`) when appending system-generated data to the context window.\n\nLarge Language Models possess a high mechanical affinity for XML boundary demarcation. By segregating raw conversational text from background technical operations using explicit tags, the system establishes a hard partition. This significantly mitigates prompt injection vectors, reduces contextual hallucination, and ensures the model accurately separates 'what the user said' from 'what the system is instructing it to know'.",
        "Data Residency and End User Agreement": "All user-generated strings, including memory sequences and API keys, are subjected to symmetric Fernet encryption prior to disc residency.\n\nBy configuring external inference endpoints, you acknowledge the terms of service of the respective API provider (Google LLC, OpenRouter, etc.)."
    },
    "7. Command Reference": {
        "Administration": "- `/session config`: Opens the interface to initialise standard or Freewill sessions.\n- `/suspend`: Terminates the active session and flushes the buffer.\n- `/purge`: Executes a bulk message deletion operation and recursively scrubs associated internal memory indices.\n- `/profile speak`: Forces an anonymous execution of a designated profile payload. (Requires Webhook/Child Bot delivery).",
        "Configuration": "- `/settings`: Private interface for API key authentication and Child Bot provisioning.\n- `/profile manage`: Central interface for profile manipulation.\n- `/profile bulk manage`: Executes batch manipulation across multiple profiles simultaneously.\n- `/profile data manage`: Interface for manual CRUD operations on vector-embedded databases (LTM/Training).",
        "Interaction": "- `/session swap`: Changes the active profile context for the current session.\n- `/profile list`: Enumerates valid user indices.\n- `/session view`: Dumps session variables and participant statuses to chat.\n- `/refresh`: Performs a targeted wipe of the channel's Short-Term Memory buffer without destroying the session structure.\n- `/whisper`: Transmits hidden variables directly to a profile's context window, eliciting an ephemeral response."
    }
}

TRANSPARENCY_CATEGORIES = {
    "1. Background Systems & Pricing": {
        "Overview": "MimicAI uses several specialized, high-speed AI models behind the scenes. This page provides transparency on what these models are, how they work, and their impact on API usage.\n\n*All prices are based on Google's pay-as-you-go tier and are calculated per 1 million tokens. A \"token\" is a piece of a word; roughly 750 words are equal to 1,000 tokens.*",
        "Long-Term Memories & Safety": "**Purpose:**\n- **Memory Creation (LTM):** Summarizes conversations to create long-term memories.\n- **Safety:** Moderates content for public profiles.\n\n**Pricing Impact:**\nUses `gemini-flash-lite-latest`.\n• **Input:** $0.10 / 1M tokens\n• **Output:** $0.40 / 1M tokens",
        "Grounding": "**Purpose:**\n- **Web Search (Grounding):** Retrieves real-time data from the internet to improve factual accuracy.\n\n**Pricing Impact:**\n• **Native Mode:** Handled entirely by your Primary Model. Costs are tied to that model's standard input/output rates, plus a Search API surcharge.\n• **RAG Mode:** Uses an auxiliary background model (`gemini-flash-lite-latest`) to search and summarize. Adds **one extra API call** per message.\n  • **Input:** $0.10 / 1M tokens\n  • **Output:** $0.40 / 1M tokens",
        "Image Generation": "**Purpose:**\n- **Image Generation:** Creates all images for the `!image` and `!imagine` commands.\n\n**Requirements:**\n• **Google API Key:** Required (**Paid Tier Only**). This model is not available on free-tier API keys.\n\n**Pricing Impact:**\nUses `gemini-2.5-flash-image` by default. You may change this model.\nEach use requires **two** API calls (Image Model + Chat Model). The image generation itself costs **~$0.039 per image**.",
        "Embedding": "**Purpose:**\n- **Semantic Search:** Converts text into numerical 'fingerprints' (embeddings) to power the search for LTM and Training Examples.\n- **Optimization:** Uses **Matryoshka Representation Learning** to output truncated 256-dimensional vectors, significantly reducing database size without losing accuracy.\n\n**Pricing Impact:**\nUses `gemini-embedding-001`.\nThis is the **cheapest operation** the bot performs. The cost is based on the amount of text being converted.\n• **Per 1 Million Tokens:** ~$0.15",
        "Profile Model": "**Purpose:**\n- **Conversation:** The model you actually talk to (e.g., `GOOGLE/gemini-2.5-flash`, `OPENROUTER/anthropic/claude-3-opus`).\n\n**Pricing Impact:**\nThis cost depends entirely on your selection in `/profile manage`.\n• **Google Models:** Prices vary by tier (Flash vs Pro).\n• **OpenRouter / Custom Models:** Prices are set by the provider (Anthropic, Meta, etc.). Note: Custom models *must* use RAG mode for Grounding and URL Context, as Native tools are exclusive to Google.\n• **Fallback:** If your primary model fails, the bot attempts to use your configured Fallback Model (defaulting to `gemini-flash-lite`), which incurs its own standard cost.",
        "Anti-Repetition Critic": "**Purpose:**\n- **Loop Detection:** If enabled, a lightweight model analyzes the conversation history *before* the main model replies to detect verbatim repetition loops.\n- **Quality Control:** Injects negative constraints into the system prompt to force the AI to break the loop.\n\n**Pricing Impact:**\nUses `gemini-flash-lite-latest`. If enabled, this adds **one extra API call** per message.\n• **Input:** $0.10 / 1M tokens\n• **Output:** $0.40 / 1M tokens"
    }
}

TERMS_CATEGORIES_SELF_HOSTED = {
    "1. Legal & Privacy": {
        "Terms of Service & Disclaimers": (
            "**1. Self-Hosted Instance:** This instance of MimicAI is self-hosted. The developers of the MimicAI software are not responsible for the management, data retention, or uptime of this specific bot.\n\n"
            "**2. Software License:** This software is provided under the Prosperity Public License 3.0.0. Unauthorized commercial use is prohibited.\n\n"
            "**3. Universal Disclaimers:** By using this software, you acknowledge that AI-generated content can be unpredictable and the software developers are not liable for any output produced by the underlying models.\n\n"
            "**4. Administrative Oversight:** The owner of this self-hosted instance possesses absolute oversight of all created profiles and conversational metadata. Through the `/mod` dashboard, they have the authority to modify or delete any profile, view instance-wide usage statistics, and blacklist users from interacting with the bot at their sole discretion.\n\n"
            "-# For more information, visit the website below."
        )
    }
}

TERMS_CATEGORIES_OFFICIAL = {
    "1. Legal & Privacy": {
        "Terms of Service & Disclaimers": (
            "**1. Official Instance:** This is the official, public instance of MimicAI.\n\n"
            "**2. Data & Privacy:** By interacting with this bot, you acknowledge and agree to our data retention and privacy policies. We do not use your conversations to train underlying AI models.\n\n"
            "**3. Universal Disclaimers:** AI-generated content can be unpredictable. The developers of MimicAI are not liable for any output produced by the models.\n\n"
            "**4. Administrative Oversight:** The owner of this official instance possesses absolute oversight of all created profiles and conversational metadata. Through the `/mod` dashboard, they have the authority to modify or delete any profile, view instance-wide usage statistics, and blacklist users from interacting with the bot at their sole discretion.\n\n"
            "-# For more information, visit the website below."
        )
    }
}